### PR TITLE
Sandboxed jquery has been fixed, bump version (closes #10)

### LINKED ISSUE #10: Sometimes Firefox is getting an error "Node was not found" in the beginning of test execution
It appears in asp tests and leads to `sanboxed-jquery.js`, concretely [this line](https://github.com/DevExpress/testcafe-legacy-api/blob/master/src/client/sandboxed-jquery.js#L1722). We did some research and found that Firefox doesn't append test div container to body when executing  `sanboxed-jquery.js`. We didn't find the cause of this behavior, because couldn't reproduce this problem separately, so decided put simple check before [this line](https://github.com/DevExpress/testcafe-legacy-api/blob/master/src/client/sandboxed-jquery.js#L1722)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @inikulin, @VasilyStrelyaev

### CODE REVIEW

File: src/client/sandboxed-jquery.js [hunk 1]
```diff
@@ -1719,7 +1719,11 @@ export function init (window, undefined) {
                     container.style.zoom = 1;
                 }
 
-                body.removeChild(container);
+                // NOTE: in some cases Firefox can't remove container div,
+                // because document body isn't appended it.
```
Comment (VasilyStrelyaev) [inline src/client/sandboxed-jquery.js]: > isn't appended it

what does it mean? the `div` is not in the `body`? Then it's

```
                // NOTE: in some cases, Firefox can't remove the container div
                // because it isn't appended to the document body.
```

**Comment by VasilyStrelyaev** [comment]
\r-

File: src/client/sandboxed-jquery.js [hunk 2]
```diff
@@ -1719,7 +1719,11 @@ export function init (window, undefined) {
                     container.style.zoom = 1;
                 }
 
-                body.removeChild(container);
+                // NOTE: in some cases Firefox can't remove container div,
```
Comment (AlexanderMoskovkin) [inline src/client/sandboxed-jquery.js]: I suppose we should add a more specific comment here, like:
`Sometimes in Firefox the "body.insertBefore(container, body.firstChild)" script above doesn't insert a container (it looks it depends on the page loading phase). Since this behavior is unstable we should check is body contains the container`

Comment (AlexanderMoskovkin) [reply src/client/sandboxed-jquery.js]: IMHO the current version of the comment just duplicates the line of code. It doesn't describe why it happens

Comment (georgiy-abbasov) [reply src/client/sandboxed-jquery.js]: Maybe it's better to place a link to this [comment](https://github.com/DevExpress/testcafe-legacy-api/issues/10#issue-174244330) ?

Comment (AlexanderMoskovkin) [reply src/client/sandboxed-jquery.js]: I don't think so. The comment in the issue contains the same info I've written above and doesn't contain any additional info

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
ping @inikulin
